name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  validate:
    name: ✅ Validate Bash Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Validar sintaxe do status-check.sh
        run: bash -n status-check.sh

  test:
    name: 🧪 Run Tests
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Simular execução de testes
        run: |
          echo "Running tests"
          exit 0

  package:
    name: 📦 Package Report
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Criar arquivo report.zip
        run: |
          mkdir -p report
          echo "CI Report generated at $(date)" > report/info.txt
          zip -r report.zip report/

      - name: Fazer upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: ci-report
          path: report.zip
