name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

env:
  ACTIONS_STEP_DEBUG: true   

jobs:
  validate:
    name: ✅ Validate Bash Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Validar sintaxe do status-check.sh
        id: validate-step
        run: |
          if ! bash -n status-check.sh; then
            echo "::error::Erro na sintaxe do script status-check.sh"
            exit 1
          else
            echo "::warning::Validação concluída sem erros"
          fi

  test:
    name: 🧪 Run Tests
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Simular execução de testes
        id: test-step
        run: |
          echo "Running tests"
          echo "::warning::Teste simulado com sucesso"
          exit 0

  package:
    name: 📦 Package Report
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Criar arquivo report.zip
        run: |
          mkdir -p report
          echo "CI Report gerado em $(date)" > report/info.txt
          zip -r report.zip report/

      - name: Fazer upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: ci-report
          path: report.zip

  summary:
    name: 📋 Job Summary
    runs-on: ubuntu-latest
    needs: package

    steps:
      - name: Mostrar resumo do job
        run: |
          echo "Runner OS: ${{ runner.os }}"
          echo "Branch/Ref: ${{ github.ref_name }}"
          echo "Validação: ${{ needs.validate.result }}"
          echo "Testes: ${{ needs.test.result }}"
          echo "Pacote: ${{ needs.package.result }}"
          echo "Link do artefato: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          echo "::warning::Confira o link do artefato para download"
